apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        {{ include "cs.image" . }}
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        ports:
          - containerPort: {{ .Values.containerPort.port }}
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: "{{ .value }}"
          {{- end }}
        volumeMounts:
          {{- range .Values.volumeMount }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
          {{- end }}
      volumes:
      - name: {{ .Values.volume.name }}
        configMap:
          name: {{ .Values.volume.name }}
