on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        
    - name: create namespace
      run: kubectl create ns cs-1-6 || true
    
    - name: install by helm
      run: | 
        helm repo add repo-cs https://github.com/alitaheri1985/cs-1-6.git
        helm install cs-1-6 repo-cs
